name: Build Obfuscate BPB Panel

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: |
          npm install -g javascript-obfuscator
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Fetch and download latest worker.js
        id: fetch
        run: |
          # Get the latest release info from GitHub API
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases/latest)
          LATEST_VERSION=$(echo "$LATEST_RELEASE" | jq -r '.tag_name')
          LATEST_URL=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name == "worker.js") | .browser_download_url')

          # Get the latest pre-release info from GitHub API
          PRERELEASE=$(curl -s https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases | jq -r 'map(select(.prerelease == true)) | first')
          PRERELEASE_VERSION=$(echo "$PRERELEASE" | jq -r '.tag_name')
          PRERELEASE_URL=$(echo "$PRERELEASE" | jq -r '.assets[] | select(.name == "worker.js") | .browser_download_url')

          # Compare versions and download the latest one
          if [ "$PRERELEASE_VERSION" \> "$LATEST_VERSION" ]; then
            DOWNLOAD_URL="$PRERELEASE_URL"
            VERSION="$PRERELEASE_VERSION"
            RELEASE_TYPE="测试版"
          else
            DOWNLOAD_URL="$LATEST_URL"
            VERSION="$LATEST_VERSION"
            RELEASE_TYPE="正式版"
          fi

          # Set environment variables for commit message
          echo "RELEASE_TYPE=$RELEASE_TYPE" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          # Download the file
          wget -O origin.js "$DOWNLOAD_URL"
          ls -l origin.js
          head -n 10 origin.js

      - name: Obfuscate BPB worker js
        run: |
          javascript-obfuscator origin.js --output _worker.js \
            --compact true \
            --identifier-names-generator hexadecimal \
            --rename-globals true \
            --string-array false \
            --string-array-encoding 'base64' \
            --string-array-threshold 0.75 \
            --transform-object-keys false \
            --self-defending false \
            --simplify true

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ":arrow_up: 更新到${{ env.RELEASE_TYPE }} bpb 面板 ${{ env.VERSION }} ✅"
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          push_options: '--set-upstream'
